define(["config/rfz"], function(RFZ) {
  console.log("payments");
  RFZ.controller("Payments", ["$scope", function Payments($scope) {
    $scope.payments = [[{amount : 12.40,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 2000.20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 150,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 200.76,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 1167.87,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 75.5,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 120,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"}],
                       [{amount : 12.40,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 120,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"}],
                       [{amount : 12.40,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 2000.20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 150,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 200.76,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 1167.87,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 75.5,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 120,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"}],
                       [{amount : 12.40,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 2000.20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 150,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 200.76,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 1167.87,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 75.5,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 120,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"}],
                       [{amount : 12.40,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 2000.20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 150,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 200.76,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 1167.87,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 75.5,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 20,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"},
                        {amount : 120,
                         created : new Date(),
                         accountId : 1,
                         status : "paid"}]];
    $scope.startPage = $scope.payments.length - 1;

    $scope.paymentAccount = function(payment) {
      return {name : "Citi ThankYou Preferred Card 2 (7874)"};
    }

    $scope.scrollToMonth = function(month) {
      var index = $scope.payments.indexOf(month);
      $scope.startPage = index;
    }
  }]);
});
